### ISSUE TITLE
how do I add multiple led strips

### ISSUE THREAD

**Issue by antoine1293** [manfredipist/homebridge-gpio-rgb-ledstrip#5]
hello  
thank you for this plugin it is great, the answer to issue #3 was particularly use-full. 
just another question do you have a way to add multiple led strips to Homebridge, if not would this be something you would consider adding to this plugin please?

**Comment by manfredipist** [comment]
Hi, i'm glad you like it. To answer your question, afaik it should be possible to instantiate multiple accessories with the same plugin. Something like this:

```
"accessories": [
     {
       "accessory": "SmartLedStrip",
       "name": "Bedroom LedStrip",
       "rPin": 22,
       "gPin": 27,
       "bPin": 17
     },
     {
       "accessory": "SmartLedStrip",
       "name": "Kitchen LedStrip",
       "rPin": 23,
       "gPin": 24,
       "bPin": 25
     }
   ]
```

Let me know if this solves your problem :)

**Comment by manfredipist** [comment]
Since any new problem has been reported, i'm going to mark this issue as solved
