### ISSUE TITLE
Get this error when install the plugin

### ISSUE THREAD

**Issue by neiltonkdf** [manfredipist/homebridge-gpio-rgb-ledstrip#6]
<img width="1304" alt="image" src="https://user-images.githubusercontent.com/18465932/83997474-d844c300-a934-11ea-8e09-5f6e36e21c1e.png">

**Comment by neiltonkdf** [comment]
after reinstall get this

<img width="804" alt="image" src="https://user-images.githubusercontent.com/18465932/83998533-34a8e200-a937-11ea-9fa6-b924b011a904.png">

**Comment by manfredipist** [comment]
Hello, please refer to the original issue post #3

**Comment by InZan3** [comment]
Same Issue here with prebuild Homebridge Image
